
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Proyecto;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 20;
  public static final int RBLOQUE = 12;
  public static final int PLUS = 18;
  public static final int RPAREN = 23;
  public static final int INT = 5;
  public static final int SEMI = 17;
  public static final int CHAR = 6;
  public static final int DIVI = 16;
  public static final int IDENTIFIER = 9;
  public static final int LPAREN = 22;
  public static final int LBLOQUE = 11;
  public static final int STRING_LITERAL = 10;
  public static final int BOOLEAN = 3;
  public static final int COMA = 19;
  public static final int STRING = 7;
  public static final int FLOAT = 8;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int BREAK = 4;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int ABSTRACT = 2;
  public static final int INTEGER_LITERAL = 25;
  public static final int EQEQ = 14;
  public static final int UMINUS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABSTRACT",
  "BOOLEAN",
  "BREAK",
  "INT",
  "CHAR",
  "STRING",
  "FLOAT",
  "IDENTIFIER",
  "STRING_LITERAL",
  "LBLOQUE",
  "RBLOQUE",
  "EQ",
  "EQEQ",
  "MINUS",
  "DIVI",
  "SEMI",
  "PLUS",
  "COMA",
  "TIMES",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "INTEGER_LITERAL"
  };
}

