
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Proyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bool = 31;
  public static final int LBLOQUE = 9;
  public static final int True = 26;
  public static final int RBLOQUE = 10;
  public static final int STRING_LITERAL = 8;
  public static final int resta = 43;
  public static final int suma = 40;
  public static final int CHAR = 7;
  public static final int forC = 53;
  public static final int conjuncion = 48;
  public static final int UMINUS = 13;
  public static final int disyuncion = 49;
  public static final int LPAREN = 14;
  public static final int SEMI = 12;
  public static final int coma = 50;
  public static final int igual = 39;
  public static final int comentCerrad = 24;
  public static final int INT = 5;
  public static final int mainC = 52;
  public static final int equivalente = 38;
  public static final int inC = 62;
  public static final int multiplicacion = 42;
  public static final int letra = 28;
  public static final int string = 4;
  public static final int RPAREN = 15;
  public static final int caracter = 30;
  public static final int menorIgual = 34;
  public static final int BOOL = 2;
  public static final int printC = 61;
  public static final int menor = 32;
  public static final int doC = 54;
  public static final int aumento = 37;
  public static final int EOF = 0;
  public static final int ident = 29;
  public static final int mayorIgual = 35;
  public static final int error = 1;
  public static final int elifC = 58;
  public static final int mayor = 33;
  public static final int False = 27;
  public static final int negacion = 44;
  public static final int NUMBER = 63;
  public static final int BREAK = 3;
  public static final int punto = 51;
  public static final int finalExpre = 25;
  public static final int potencia = 47;
  public static final int elseC = 57;
  public static final int aperturaP = 20;
  public static final int FLOAT = 6;
  public static final int diferente = 36;
  public static final int cerraduraP = 21;
  public static final int decremento = 41;
  public static final int ifC = 56;
  public static final int comentarioL = 22;
  public static final int comentApert = 23;
  public static final int STRING = 11;
  public static final int whileC = 55;
  public static final int returnC = 60;
  public static final int aperturaC = 18;
  public static final int FLOAT_LITERAL = 65;
  public static final int aperturaB = 16;
  public static final int division = 45;
  public static final int cerraduraC = 19;
  public static final int inputC = 59;
  public static final int cerraduraB = 17;
  public static final int modulo = 46;
  public static final int INTEGER_LITERAL = 64;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "BREAK",
  "string",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING_LITERAL",
  "LBLOQUE",
  "RBLOQUE",
  "STRING",
  "SEMI",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "aperturaB",
  "cerraduraB",
  "aperturaC",
  "cerraduraC",
  "aperturaP",
  "cerraduraP",
  "comentarioL",
  "comentApert",
  "comentCerrad",
  "finalExpre",
  "True",
  "False",
  "letra",
  "ident",
  "caracter",
  "bool",
  "menor",
  "mayor",
  "menorIgual",
  "mayorIgual",
  "diferente",
  "aumento",
  "equivalente",
  "igual",
  "suma",
  "decremento",
  "multiplicacion",
  "resta",
  "negacion",
  "division",
  "modulo",
  "potencia",
  "conjuncion",
  "disyuncion",
  "coma",
  "punto",
  "mainC",
  "forC",
  "doC",
  "whileC",
  "ifC",
  "elseC",
  "elifC",
  "inputC",
  "returnC",
  "printC",
  "inC",
  "NUMBER",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL"
  };
}

